"<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hidded' in 'where clause' in C:\wamp64\www\document-tracker\backend\datatables\admin\dashboard.php on line <i>31</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hidded' in 'where clause' in C:\wamp64\www\document-tracker\backend\datatables\admin\dashboard.php on line <i>31</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>385704</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\document-tracker\backend\datatables\admin\dashboard.php' bgcolor='#eeeeec'>...\dashboard.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0146</td><td bgcolor='#eeeeec' align='right'>434640</td><td bgcolor='#eeeeec'><a href='http://www.php.net/PDO.prepare' target='_new'>prepare</a>( <span>$query = </span><span>&#39;SELECT * FROM documents WHERE is_deleted = 0 AND hidded = 0\r\n        AND (sender LIKE &quot;%%&quot;\r\n        OR reference LIKE &quot;%%&quot; \r\n        OR document LIKE &quot;%%&quot; \r\n        OR type LIKE &quot;%%&quot; \r\n        OR status LIKE &quot;%%&quot; )\r\n        ORDER BY id desc &#39;</span> )</td><td title='C:\wamp64\www\document-tracker\backend\datatables\admin\dashboard.php' bgcolor='#eeeeec'>...\dashboard.php<b>:</b>31</td></tr>
</table></font>
"