<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_deleted' in 'where clause' in C:\wamp64\www\document-tracker\backend\class\Category.php on line <i>16</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_deleted' in 'where clause' in C:\wamp64\www\document-tracker\backend\class\Category.php on line <i>16</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>367040</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\document-tracker\backend\class\Category.php' bgcolor='#eeeeec'>...\Category.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0142</td><td bgcolor='#eeeeec' align='right'>417176</td><td bgcolor='#eeeeec'>Category->add_category( <span>$category = </span><span>&#39;test&#39;</span>, <span>$details = </span><span>&#39;tesy&#39;</span>, <span>$max_time = </span><span>&#39;6&#39;</span> )</td><td title='C:\wamp64\www\document-tracker\backend\class\Category.php' bgcolor='#eeeeec'>...\Category.php<b>:</b>113</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0142</td><td bgcolor='#eeeeec' align='right'>417176</td><td bgcolor='#eeeeec'><a href='http://www.php.net/PDO.prepare' target='_new'>prepare</a>( <span>$query = </span><span>&#39;SELECT * FROM category WHERE category = :category AND is_deleted = 0&#39;</span> )</td><td title='C:\wamp64\www\document-tracker\backend\class\Category.php' bgcolor='#eeeeec'>...\Category.php<b>:</b>16</td></tr>
</table></font>